=== Yacineos/cabinet/src/xsd/cabinetInfirmier.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
           xmlns = "http://www.ujf-grenoble.fr/l3miage/medical"
           elementFormDefault="qualified">
           
    <!-- déclaration cabinet infirmier-->
    <xs:element name="cabinet" type="Cabinet" />
    <!-- définition du cabinet -->
    <xs:complexType name="Cabinet" >
        <xs:sequence>
            <!-- on peut déclarer type NOMCabinet-->
            <xs:element name="nom" type="Nom"/>
            <xs:element name="adresse" type="Adresse"/>
            <xs:element name="infirmiers" type="Infirmiers" />
            <xs:element name="patients" type="Patients" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Adresse" >
        <xs:sequence>
            <xs:element name="numéro" type="xs:unsignedInt"/>
            <xs:element name="rue" type="xs:string" />
            <xs:element name="ville" type="Nom" />
            <xs:element name="codePostal" type="CodePostal"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Infirmiers">
        <xs:sequence>
            <xs:element name="infirmier" type="Infirmier"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Infirmier">
        <xs:extension base="Infirmier">
            <xs:sequence>
                <xs:element name="nom" type = "Nom" /> 
                <xs:element name="prénom" type = "Nom" /> 
                <xs:element name="photo" type = "xs:string" /> 
            </xs:sequence>
            <xs:attribute name="id" type="xs:int"/>
        </xs:extension>
        
    </xs:complexType>
    
    
    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" type="Patient"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Patient">
        <xs:sequence>
                <xs:element name="nom" type = "Nom" /> 
                <xs:element name="prénom" type = "Nom" /> 
                <xs:element name="sexe" type = "Sexe" />
                <xs:element name="naissance" type = "xs:date" /> 
                <xs:element name="numéro" type = "xs:unsignedInt" /> 
                <xs:element name="adresse" type = "Adresse" />  
                <xs:element name="visite" type = "Visite" /> 
            </xs:sequence>
    </xs:complexType>
    
    <simpleType name ="Nom">
        <!-- on commence par Maj et puis on a jsuqua 50 char et puis on a soit un espace ou bien 
              un tiert soit rien , 
        -->
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{1}[a-z]{0,50}[[ -]{0,1}[A-Z]{0,1}[a-z]{1,50}]{0,10}" />"
        </xs:restriction>
    </simpleType>
    
    <simpleType name ="Sexe">
        <!-- on commence par Maj et puis on a jsuqua 50 char et puis on a soit un espace ou bien 
              un tiert soit rien , 
        -->
        <xs:restriction base="xs:string">
            <xs:pattern value="[MF]{1}" />"
        </xs:restriction>
    </simpleType>
    
    <simpleType name ="CodePostal">
        <!-- on commence par Maj et puis on a jsuqua 50 char et puis on a soit un espace ou bien 
              un tiert soit rien , 
        -->
        <xs:restriction base="xs:int">
            <xs:pattern value="/d{5}" />"
        </xs:restriction>
    </simpleType>
    
    
    <xs:simpleType name="NumSecu">
        <xs:restriction base="xs:string">
            <xs:pattern value="^[1-478][0-9]{2}([0235-9][0-9]|[14][0-2])(([013-9][0-9]|[2][0-9AB])([0]{2}[1-9]|[0-9][1-9]{2}|[1-9][0-9]{2}))([0]{2}[1-9]|[0-9][1-9]{2}|[1-9][0-9]{2})([0-8][0-9]|[9][0-7])">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Visite">
        <xs:extension base="Visite">
            <xs:sequence>
                <xs:element name="nom" type = "Nom" /> 
            </xs:sequence>
            <xs:attribute name="date" type="xs:date"/>
            <xs:attribute name="intervenant" type="xs:unsignedInt"/>
        </xs:extension>
     </xs:complexType>
</xs:schema>

=== Yacineos/cabinet/src/xml/cabinetInfirmier.xml
<?xml version="1.0" encoding="UTF-8"?>


<cabinet xmlns="http://www.ujf-grenoble.fr/l3miage/medical" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://www.ujf-grenoble.fr/l3miage/medical ../xsd/cabinetInfirmier.xsd" >
    <nom>Soins a Grenoble</nom>
    <adresse>
        <numéro>60</numéro>
        <rue>rue de la Chimie</rue>
        <ville>Grenoble</ville>
        <codePostal>38041</codePostal>
        
    </adresse>
    <infirmiers>
        <infirmier id="001">
            <nom>Freechie</nom>
            <prénom>Sarah</prénom>
            <photo>sarah.png</photo>
        </infirmier>
        <infirmier id="002">
            <nom>Stickee</nom>
            <prénom>Sophie</prénom>
            <photo>sophie.png</photo>
        </infirmier>
        <infirmier id="003">
            <nom>Ochon</nom>
            <prénom>Paul</prénom>
            <photo>paul.png</photo>
        </infirmier>
    </infirmiers>
    <patients>
        <patient>
            <!-- Homme , né en août 98 en France , à Marseille (numéro 55 en bouche du rhône) 458e naissance -->
            <nom>Alcole</nom>
            <prénom>Yvon</prénom>
            <sexe>F</sexe>
            <naissance>1998-08-22</naissance>
            <numéro>198082205545852</numéro>
            <adresse>
                <étage>6</étage>
                <numéro>50</numéro>
                <rue>avenue Félix Viallet</rue>
                <ville>Grenoble</ville>
                <codePostal>38031</codePostal>
            </adresse>
            <visite date="2015-12-08" intervenant="001">
                <acte id="109"/>
            </visite>
        </patient>
        <patient>
            <!--Elvire est née le 08 mars 82 en France, à Lyon (n° 23 dans le rhône), il s'agissait de la 52e naissance-->
            <nom>Orouge</nom>
            <prénom>Elvire</prénom>
            <sexe>F</sexe>
            <naissance>1982-03-08</naissance>
            <numéro>282036902305218</numéro>
            <adresse>
                <étage></étage>
                <numéro></numéro>
                <rue>Rond-Point de la Croix de Vie</rue>
                <ville>La Tronche</ville>
                <codePostal>38700</codePostal>
            </adresse>
            <visite date="2015-12-08" intervenant="002" >
                <acte id="300"/>   
            </visite>
        </patient>
        <patient>
            <!-- Oscare est née le 25 mars 75 en France, à Chambéry (n° 65 dans la Savoie) Il s'agissait de la 692e naissance -->
            <nom>Pien</nom>
            <prénom>Oscare</prénom>
            <sexe>F</sexe>
            <naissance>1975-03-25</naissance>
            <numéro>275037306569202</numéro>
            <adresse>
                <étage></étage>
                <numéro></numéro>
                <rue>rue Casimir Brenier</rue>
                <ville>Grenoble</ville>
                <codePostal>38000</codePostal>
            </adresse>
            <visite date="2015-12-08" intervenant="002">
                <acte id="104"/>
                <acte id="105"/>  
            </visite>
            
        </patient>
        <patient>
            <!-- né le 02 août 2011 en France, à Bordeaux (n° 63 dans la Gironde). Il s'agi de la 35e naissance. -->
            <nom>Kapoetla</nom>
            <prénom>Xavier</prénom>
            <sexe>F</sexe>
            <naissance>2011-08-02</naissance>
            <numéro>111083306303521</numéro>
            <adresse>
                <étage></étage>
                <numéro>25</numéro>
                <rue>rue des Martyrs</rue>
                <ville>Grenoble</ville>
                <codePostal>38042</codePostal>
            </adresse>
            <visite date="2015-12-08" intervenant="002">
                <acte id="111"/>
            </visite>
            
        </patient>
    </patients>
</cabinet>
